// mealsSlice.js

import { createSlice } from "@reduxjs/toolkit";

// Define the mealsSlice, which manages the selection state of meals
export const mealsSlice = createSlice({
  name: "meals", // Name of the slice
  initialState: [
    // Initial state of the meals, with each meal having a name, cost, and selected status
    { name: "Breakfast", cost: 50, selected: false },
    { name: "High Tea", cost: 25, selected: false },
    { name: "Lunch", cost: 65, selected: false },
    { name: "Dinner", cost: 70, selected: false },
  ],

  // Reducers to handle state changes
  reducers: {
    // Toggle the 'selected' status of a meal based on the provided index
    toggleMealSelection: (state, action) => {
      // Toggles the 'selected' property of the meal at the given index
      state[action.payload].selected = !state[action.payload].selected;
    },
  },
});

// Export the action creators generated by createSlice
export const { toggleMealSelection } = mealsSlice.actions;

// Export the reducer to be included in the Redux store
export default mealsSlice.reducer;
