// venueSlice.js

import { createSlice } from "@reduxjs/toolkit";

// Define the slice for managing venue-related state, which includes an initial list of venues and actions to modify them
export const venueSlice = createSlice({
  name: "venue", // Name of the slice, which corresponds to the state property in the Redux store
  initialState: [
    // Initial state array containing venue objects, each with image URL, name, cost, and quantity
    {
      img: "https://pixabay.com/images/download/chairs-2181916_640.jpg",
      name: "Conference Room (Capacity:15)",
      cost: 3500,
      quantity: 0,
    },
    {
      img: "https://pixabay.com/images/download/event-venue-1597531_640.jpg",
      name: "Auditorium Hall (Capacity:200)",
      cost: 5500,
      quantity: 0,
    },
    {
      img: "https://pixabay.com/images/download/convention-center-3908238_640.jpg",
      name: "Presentation Room (Capacity:50)",
      cost: 700,
      quantity: 0,
    },
    {
      img: "https://pixabay.com/images/download/chairs-2181916_640.jpg",
      name: "Large Meeting Room (Capacity:10)",
      cost: 900,
      quantity: 0,
    },
    {
      img: "https://pixabay.com/images/download/laptops-593296_640.jpg",
      name: "Small Meeting Room (Capacity:5)",
      cost: 1100,
      quantity: 0,
    },
  ],
  reducers: {
    // Reducer to increment the quantity of a specific venue item by index
    incrementQuantity: (state, action) => {
      const { payload: index } = action; // Extract index from action payload
      if (state[index]) {
        // Check if the venue exists at the given index
        if (
          state[index].name === " Auditorium Hall (Capacity:200)" &&
          state[index].quantity >= 3
        ) {
          // Prevent adding more than 3 Auditorium Hall bookings
          return;
        }
        state[index].quantity++; // Increment the quantity for the specified venue
      }
    },
    // Reducer to decrement the quantity of a specific venue item by index
    decrementQuantity: (state, action) => {
      const { payload: index } = action; // Extract index from action payload
      if (state[index] && state[index].quantity > 0) {
        // Check if the venue exists and has a quantity greater than 0
        state[index].quantity--; // Decrement the quantity for the specified venue
      }
    },
  },
});

// Export actions generated by createSlice for use in dispatching state changes
export const { incrementQuantity, decrementQuantity } = venueSlice.actions;

// Export the reducer function to be combined in the Redux store
export default venueSlice.reducer;
